### ISSUE TITLE
Please update dependencies

### ISSUE THREAD

**Issue by anselmic** [voxpupuli/puppet-rkhunter#22]
Please update the dependency for stdlib 8.x

Thanks.
C

**Comment by anselmic** [comment]
Is this still maintained?

**Comment by zilchms** [comment]
Yes, just fell a bit under the radar. You are welcome to help maintain it (especially if you want to see features or specific updates) by submitting PRs :)

**Comment by zilchms** [comment]
Stdlib dependency update should now be merged with #24
